/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("INFOBOX_DListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheINFOBOX_DListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheINFOBOX_DListGenerated.onFilterBar().iCheckFilterField({ property: "Firstname" });
            Then.onTheINFOBOX_DListGenerated.onFilterBar().iCheckFilterField({ property: "Lastname" });
            Then.onTheINFOBOX_DListGenerated.onFilterBar().iCheckFilterField({ property: "Secondname" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheINFOBOX_DListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheINFOBOX_DListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheINFOBOX_DListGenerated.onTable(defaultTableId).iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheINFOBOX_DListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"Photo":{"header":"Фото"},"Telnum":{"header":"Телефон"},"Firstname":{"header":"Ім''я"},"Lastname":{"header":"Прізвище"},"Secondname":{"header":"По батькові"},"Datebirth":{"header":"Дата народження"},"Organization":{"header":"Організація"},"Department":{"header":"Департамент"},"Unit":{"header":"Підрозділ"},"Positions":{"header":"Посада"},"Dateofadoption":{"header":"Дата приняття"},"Status":{"header":"Статус"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheINFOBOX_DListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheINFOBOX_DListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheINFOBOX_DListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheINFOBOX_DObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});