/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("INFOBOX_DObjectPageObjectPage journey");

        opaTest("Navigate to INFOBOX_DObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheINFOBOX_DListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheINFOBOX_DListGenerated.onTable().iCheckRows();
            When.onTheINFOBOX_DListGenerated.onTable().iPressRow(0);

            Then.onTheINFOBOX_DObjectPageGenerated.iSeeThisPage();
        });


        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onTheINFOBOX_DObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "DataPoint::_FN" });
            Then.onTheINFOBOX_DObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "DataPoint::_LN" });
            Then.onTheINFOBOX_DObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "DataPoint::_SN" });
        });

        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheINFOBOX_DObjectPageGenerated.iCheckSection({ section: "GeneralInfo" });
            //When.onTheINFOBOX_DObjectPageGenerated.iGoToSection({ section: "GeneralInfo", subSection: "FieldGroup::_data" });
            Then.onTheINFOBOX_DObjectPageGenerated.iCheckSubSection({ section: "FieldGroup::_data" });
            Then.onTheINFOBOX_DObjectPageGenerated.onForm({ section: "FieldGroup::_data" }).iCheckField({ property: "Firstname" });
            Then.onTheINFOBOX_DObjectPageGenerated.onForm({ section: "FieldGroup::_data" }).iCheckField({ property: "Lastname" });
            Then.onTheINFOBOX_DObjectPageGenerated.onForm({ section: "FieldGroup::_data" }).iCheckField({ property: "Secondname" });
            //When.onTheINFOBOX_DObjectPageGenerated.iGoToSection({ section: "GeneralInfo", subSection: "FieldGroup::_data2" });
            Then.onTheINFOBOX_DObjectPageGenerated.iCheckSubSection({ section: "FieldGroup::_data2" });
            Then.onTheINFOBOX_DObjectPageGenerated.onForm({ section: "FieldGroup::_data2" }).iCheckField({ property: "Telnum" });
            Then.onTheINFOBOX_DObjectPageGenerated.onForm({ section: "FieldGroup::_data2" }).iCheckField({ property: "Datebirth" });
            Then.onTheINFOBOX_DObjectPageGenerated.onForm({ section: "FieldGroup::_data2" }).iCheckField({ property: "Organization" });
            Then.onTheINFOBOX_DObjectPageGenerated.onForm({ section: "FieldGroup::_data2" }).iCheckField({ property: "Department" });
            Then.onTheINFOBOX_DObjectPageGenerated.onForm({ section: "FieldGroup::_data2" }).iCheckField({ property: "Unit" });
            Then.onTheINFOBOX_DObjectPageGenerated.onForm({ section: "FieldGroup::_data2" }).iCheckField({ property: "Positions" });
            Then.onTheINFOBOX_DObjectPageGenerated.onForm({ section: "FieldGroup::_data2" }).iCheckField({ property: "Dateofadoption" });
            Then.onTheINFOBOX_DObjectPageGenerated.onForm({ section: "FieldGroup::_data2" }).iCheckField({ property: "Status" });
            //When.onTheINFOBOX_DObjectPageGenerated.iGoToSection({ section: "GeneralInfo", subSection: "FieldGroup::Upload" });
            Then.onTheINFOBOX_DObjectPageGenerated.iCheckSubSection({ section: "FieldGroup::Upload" });
            Then.onTheINFOBOX_DObjectPageGenerated.onForm({ section: "FieldGroup::Upload" }).iCheckField({ property: "Attachment" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});